import { Inter } from "next/font/google";
import "./globals.css";
import "tw-elements-react/dist/css/tw-elements-react.min.css";
import Navbar from "@/app/ui/navbar";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { session } }) {
  return (
      <SessionWrapper>
          <html lang="en">
            <body className={inter.className}>
              <Navbar/>
              {children}
            </body>
          </html>
      </SessionWrapper>
  );
}
